package com.sodyu.elasticsearch.dal.dao;

import com.sodyu.elasticsearch.dal.entity.Dianpu;
import com.sodyu.elasticsearch.dal.entity.DianpuExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface DianpuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    @SelectProvider(type=DianpuSqlProvider.class, method="countByExample")
    int countByExample(DianpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    @DeleteProvider(type=DianpuSqlProvider.class, method="deleteByExample")
    int deleteByExample(DianpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    @Delete({
        "delete from dianpu",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    @Insert({
        "insert into dianpu (id, uid, ",
        "shopId, shopName, ",
        "saleCount, productCount, ",
        "shopUrl, shopRealUrl, ",
        "goodratePercent, mainAuction, ",
        "location, telephone, ",
        "type, category, ",
        "destination, allkeys, ",
        "DataChange_CreateUser, DataChange_CreateTime, ",
        "DataChange_LastUser, DataChange_LastTime)",
        "values (#{id,jdbcType=BIGINT}, #{uid,jdbcType=VARCHAR}, ",
        "#{shopId,jdbcType=VARCHAR}, #{shopName,jdbcType=VARCHAR}, ",
        "#{saleCount,jdbcType=VARCHAR}, #{productCount,jdbcType=VARCHAR}, ",
        "#{shopUrl,jdbcType=VARCHAR}, #{shopRealUrl,jdbcType=VARCHAR}, ",
        "#{goodratePercent,jdbcType=VARCHAR}, #{mainAuction,jdbcType=VARCHAR}, ",
        "#{location,jdbcType=VARCHAR}, #{telephone,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{category,jdbcType=VARCHAR}, ",
        "#{destination,jdbcType=VARCHAR}, #{allkeys,jdbcType=VARCHAR}, ",
        "#{dataChange_CreateUser,jdbcType=VARCHAR}, #{dataChange_CreateTime,jdbcType=TIMESTAMP}, ",
        "#{dataChange_LastUser,jdbcType=VARCHAR}, #{dataChange_LastTime,jdbcType=TIMESTAMP})"
    })
    int insert(Dianpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    @InsertProvider(type=DianpuSqlProvider.class, method="insertSelective")
    int insertSelective(Dianpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    @SelectProvider(type=DianpuSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="uid", property="uid", jdbcType=JdbcType.VARCHAR),
        @Result(column="shopId", property="shopId", jdbcType=JdbcType.VARCHAR),
        @Result(column="shopName", property="shopName", jdbcType=JdbcType.VARCHAR),
        @Result(column="saleCount", property="saleCount", jdbcType=JdbcType.VARCHAR),
        @Result(column="productCount", property="productCount", jdbcType=JdbcType.VARCHAR),
        @Result(column="shopUrl", property="shopUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="shopRealUrl", property="shopRealUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="goodratePercent", property="goodratePercent", jdbcType=JdbcType.VARCHAR),
        @Result(column="mainAuction", property="mainAuction", jdbcType=JdbcType.VARCHAR),
        @Result(column="location", property="location", jdbcType=JdbcType.VARCHAR),
        @Result(column="telephone", property="telephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="category", property="category", jdbcType=JdbcType.VARCHAR),
        @Result(column="destination", property="destination", jdbcType=JdbcType.VARCHAR),
        @Result(column="allkeys", property="allkeys", jdbcType=JdbcType.VARCHAR),
        @Result(column="DataChange_CreateUser", property="dataChange_CreateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="DataChange_CreateTime", property="dataChange_CreateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DataChange_LastUser", property="dataChange_LastUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="DataChange_LastTime", property="dataChange_LastTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Dianpu> selectByExample(DianpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    @Select({
        "select",
        "id, uid, shopId, shopName, saleCount, productCount, shopUrl, shopRealUrl, goodratePercent, ",
        "mainAuction, location, telephone, type, category, destination, allkeys, DataChange_CreateUser, ",
        "DataChange_CreateTime, DataChange_LastUser, DataChange_LastTime",
        "from dianpu",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="uid", property="uid", jdbcType=JdbcType.VARCHAR),
        @Result(column="shopId", property="shopId", jdbcType=JdbcType.VARCHAR),
        @Result(column="shopName", property="shopName", jdbcType=JdbcType.VARCHAR),
        @Result(column="saleCount", property="saleCount", jdbcType=JdbcType.VARCHAR),
        @Result(column="productCount", property="productCount", jdbcType=JdbcType.VARCHAR),
        @Result(column="shopUrl", property="shopUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="shopRealUrl", property="shopRealUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="goodratePercent", property="goodratePercent", jdbcType=JdbcType.VARCHAR),
        @Result(column="mainAuction", property="mainAuction", jdbcType=JdbcType.VARCHAR),
        @Result(column="location", property="location", jdbcType=JdbcType.VARCHAR),
        @Result(column="telephone", property="telephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="category", property="category", jdbcType=JdbcType.VARCHAR),
        @Result(column="destination", property="destination", jdbcType=JdbcType.VARCHAR),
        @Result(column="allkeys", property="allkeys", jdbcType=JdbcType.VARCHAR),
        @Result(column="DataChange_CreateUser", property="dataChange_CreateUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="DataChange_CreateTime", property="dataChange_CreateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DataChange_LastUser", property="dataChange_LastUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="DataChange_LastTime", property="dataChange_LastTime", jdbcType=JdbcType.TIMESTAMP)
    })
    Dianpu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    @UpdateProvider(type=DianpuSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Dianpu record, @Param("example") DianpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    @UpdateProvider(type=DianpuSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Dianpu record, @Param("example") DianpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    @UpdateProvider(type=DianpuSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Dianpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    @Update({
        "update dianpu",
        "set uid = #{uid,jdbcType=VARCHAR},",
          "shopId = #{shopId,jdbcType=VARCHAR},",
          "shopName = #{shopName,jdbcType=VARCHAR},",
          "saleCount = #{saleCount,jdbcType=VARCHAR},",
          "productCount = #{productCount,jdbcType=VARCHAR},",
          "shopUrl = #{shopUrl,jdbcType=VARCHAR},",
          "shopRealUrl = #{shopRealUrl,jdbcType=VARCHAR},",
          "goodratePercent = #{goodratePercent,jdbcType=VARCHAR},",
          "mainAuction = #{mainAuction,jdbcType=VARCHAR},",
          "location = #{location,jdbcType=VARCHAR},",
          "telephone = #{telephone,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR},",
          "category = #{category,jdbcType=VARCHAR},",
          "destination = #{destination,jdbcType=VARCHAR},",
          "allkeys = #{allkeys,jdbcType=VARCHAR},",
          "DataChange_CreateUser = #{dataChange_CreateUser,jdbcType=VARCHAR},",
          "DataChange_CreateTime = #{dataChange_CreateTime,jdbcType=TIMESTAMP},",
          "DataChange_LastUser = #{dataChange_LastUser,jdbcType=VARCHAR},",
          "DataChange_LastTime = #{dataChange_LastTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Dianpu record);
}