package com.sodyu.elasticsearch.dal.entity;

import java.util.Date;

public class Dianpu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.id
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.uid
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.shopId
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.shopName
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.saleCount
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String saleCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.productCount
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String productCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.shopUrl
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String shopUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.shopRealUrl
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String shopRealUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.goodratePercent
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String goodratePercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.mainAuction
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String mainAuction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.location
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.telephone
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.type
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.category
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.destination
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.allkeys
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String allkeys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.DataChange_CreateUser
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String dataChange_CreateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.DataChange_CreateTime
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private Date dataChange_CreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.DataChange_LastUser
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private String dataChange_LastUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianpu.DataChange_LastTime
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    private Date dataChange_LastTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.id
     *
     * @return the value of dianpu.id
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.id
     *
     * @param id the value for dianpu.id
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.uid
     *
     * @return the value of dianpu.uid
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.uid
     *
     * @param uid the value for dianpu.uid
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.shopId
     *
     * @return the value of dianpu.shopId
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.shopId
     *
     * @param shopId the value for dianpu.shopId
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.shopName
     *
     * @return the value of dianpu.shopName
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.shopName
     *
     * @param shopName the value for dianpu.shopName
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.saleCount
     *
     * @return the value of dianpu.saleCount
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getSaleCount() {
        return saleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.saleCount
     *
     * @param saleCount the value for dianpu.saleCount
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setSaleCount(String saleCount) {
        this.saleCount = saleCount == null ? null : saleCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.productCount
     *
     * @return the value of dianpu.productCount
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.productCount
     *
     * @param productCount the value for dianpu.productCount
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setProductCount(String productCount) {
        this.productCount = productCount == null ? null : productCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.shopUrl
     *
     * @return the value of dianpu.shopUrl
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getShopUrl() {
        return shopUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.shopUrl
     *
     * @param shopUrl the value for dianpu.shopUrl
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setShopUrl(String shopUrl) {
        this.shopUrl = shopUrl == null ? null : shopUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.shopRealUrl
     *
     * @return the value of dianpu.shopRealUrl
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getShopRealUrl() {
        return shopRealUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.shopRealUrl
     *
     * @param shopRealUrl the value for dianpu.shopRealUrl
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setShopRealUrl(String shopRealUrl) {
        this.shopRealUrl = shopRealUrl == null ? null : shopRealUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.goodratePercent
     *
     * @return the value of dianpu.goodratePercent
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getGoodratePercent() {
        return goodratePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.goodratePercent
     *
     * @param goodratePercent the value for dianpu.goodratePercent
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setGoodratePercent(String goodratePercent) {
        this.goodratePercent = goodratePercent == null ? null : goodratePercent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.mainAuction
     *
     * @return the value of dianpu.mainAuction
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getMainAuction() {
        return mainAuction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.mainAuction
     *
     * @param mainAuction the value for dianpu.mainAuction
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setMainAuction(String mainAuction) {
        this.mainAuction = mainAuction == null ? null : mainAuction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.location
     *
     * @return the value of dianpu.location
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.location
     *
     * @param location the value for dianpu.location
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.telephone
     *
     * @return the value of dianpu.telephone
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.telephone
     *
     * @param telephone the value for dianpu.telephone
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.type
     *
     * @return the value of dianpu.type
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.type
     *
     * @param type the value for dianpu.type
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.category
     *
     * @return the value of dianpu.category
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.category
     *
     * @param category the value for dianpu.category
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.destination
     *
     * @return the value of dianpu.destination
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.destination
     *
     * @param destination the value for dianpu.destination
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.allkeys
     *
     * @return the value of dianpu.allkeys
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getAllkeys() {
        return allkeys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.allkeys
     *
     * @param allkeys the value for dianpu.allkeys
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setAllkeys(String allkeys) {
        this.allkeys = allkeys == null ? null : allkeys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.DataChange_CreateUser
     *
     * @return the value of dianpu.DataChange_CreateUser
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getDataChange_CreateUser() {
        return dataChange_CreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.DataChange_CreateUser
     *
     * @param dataChange_CreateUser the value for dianpu.DataChange_CreateUser
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setDataChange_CreateUser(String dataChange_CreateUser) {
        this.dataChange_CreateUser = dataChange_CreateUser == null ? null : dataChange_CreateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.DataChange_CreateTime
     *
     * @return the value of dianpu.DataChange_CreateTime
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public Date getDataChange_CreateTime() {
        return dataChange_CreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.DataChange_CreateTime
     *
     * @param dataChange_CreateTime the value for dianpu.DataChange_CreateTime
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setDataChange_CreateTime(Date dataChange_CreateTime) {
        this.dataChange_CreateTime = dataChange_CreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.DataChange_LastUser
     *
     * @return the value of dianpu.DataChange_LastUser
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getDataChange_LastUser() {
        return dataChange_LastUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.DataChange_LastUser
     *
     * @param dataChange_LastUser the value for dianpu.DataChange_LastUser
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setDataChange_LastUser(String dataChange_LastUser) {
        this.dataChange_LastUser = dataChange_LastUser == null ? null : dataChange_LastUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianpu.DataChange_LastTime
     *
     * @return the value of dianpu.DataChange_LastTime
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public Date getDataChange_LastTime() {
        return dataChange_LastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianpu.DataChange_LastTime
     *
     * @param dataChange_LastTime the value for dianpu.DataChange_LastTime
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setDataChange_LastTime(Date dataChange_LastTime) {
        this.dataChange_LastTime = dataChange_LastTime;
    }
}