package com.sodyu.elasticsearch.dal.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DianpuExample {

    protected long page=-1;

    protected long pageSize=-1;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    protected boolean distinct;


    public long getPageSize() {
        return pageSize;
    }

    public void setPageSize(long pageSize) {
        this.pageSize = pageSize;
    }

    public long getPage() {
        return page;
    }

    public void setPage(long page) {
        this.page = page;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public DianpuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        page=-1;
        pageSize=-1;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("shopId is null");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("shopId is not null");
            return (Criteria) this;
        }

        public Criteria andShopIdEqualTo(String value) {
            addCriterion("shopId =", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotEqualTo(String value) {
            addCriterion("shopId <>", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThan(String value) {
            addCriterion("shopId >", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(String value) {
            addCriterion("shopId >=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThan(String value) {
            addCriterion("shopId <", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThanOrEqualTo(String value) {
            addCriterion("shopId <=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLike(String value) {
            addCriterion("shopId like", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotLike(String value) {
            addCriterion("shopId not like", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdIn(List<String> values) {
            addCriterion("shopId in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotIn(List<String> values) {
            addCriterion("shopId not in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdBetween(String value1, String value2) {
            addCriterion("shopId between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotBetween(String value1, String value2) {
            addCriterion("shopId not between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNull() {
            addCriterion("shopName is null");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNotNull() {
            addCriterion("shopName is not null");
            return (Criteria) this;
        }

        public Criteria andShopNameEqualTo(String value) {
            addCriterion("shopName =", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotEqualTo(String value) {
            addCriterion("shopName <>", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThan(String value) {
            addCriterion("shopName >", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThanOrEqualTo(String value) {
            addCriterion("shopName >=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThan(String value) {
            addCriterion("shopName <", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThanOrEqualTo(String value) {
            addCriterion("shopName <=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLike(String value) {
            addCriterion("shopName like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotLike(String value) {
            addCriterion("shopName not like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameIn(List<String> values) {
            addCriterion("shopName in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotIn(List<String> values) {
            addCriterion("shopName not in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameBetween(String value1, String value2) {
            addCriterion("shopName between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotBetween(String value1, String value2) {
            addCriterion("shopName not between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andSaleCountIsNull() {
            addCriterion("saleCount is null");
            return (Criteria) this;
        }

        public Criteria andSaleCountIsNotNull() {
            addCriterion("saleCount is not null");
            return (Criteria) this;
        }

        public Criteria andSaleCountEqualTo(String value) {
            addCriterion("saleCount =", value, "saleCount");
            return (Criteria) this;
        }

        public Criteria andSaleCountNotEqualTo(String value) {
            addCriterion("saleCount <>", value, "saleCount");
            return (Criteria) this;
        }

        public Criteria andSaleCountGreaterThan(String value) {
            addCriterion("saleCount >", value, "saleCount");
            return (Criteria) this;
        }

        public Criteria andSaleCountGreaterThanOrEqualTo(String value) {
            addCriterion("saleCount >=", value, "saleCount");
            return (Criteria) this;
        }

        public Criteria andSaleCountLessThan(String value) {
            addCriterion("saleCount <", value, "saleCount");
            return (Criteria) this;
        }

        public Criteria andSaleCountLessThanOrEqualTo(String value) {
            addCriterion("saleCount <=", value, "saleCount");
            return (Criteria) this;
        }

        public Criteria andSaleCountLike(String value) {
            addCriterion("saleCount like", value, "saleCount");
            return (Criteria) this;
        }

        public Criteria andSaleCountNotLike(String value) {
            addCriterion("saleCount not like", value, "saleCount");
            return (Criteria) this;
        }

        public Criteria andSaleCountIn(List<String> values) {
            addCriterion("saleCount in", values, "saleCount");
            return (Criteria) this;
        }

        public Criteria andSaleCountNotIn(List<String> values) {
            addCriterion("saleCount not in", values, "saleCount");
            return (Criteria) this;
        }

        public Criteria andSaleCountBetween(String value1, String value2) {
            addCriterion("saleCount between", value1, value2, "saleCount");
            return (Criteria) this;
        }

        public Criteria andSaleCountNotBetween(String value1, String value2) {
            addCriterion("saleCount not between", value1, value2, "saleCount");
            return (Criteria) this;
        }

        public Criteria andProductCountIsNull() {
            addCriterion("productCount is null");
            return (Criteria) this;
        }

        public Criteria andProductCountIsNotNull() {
            addCriterion("productCount is not null");
            return (Criteria) this;
        }

        public Criteria andProductCountEqualTo(String value) {
            addCriterion("productCount =", value, "productCount");
            return (Criteria) this;
        }

        public Criteria andProductCountNotEqualTo(String value) {
            addCriterion("productCount <>", value, "productCount");
            return (Criteria) this;
        }

        public Criteria andProductCountGreaterThan(String value) {
            addCriterion("productCount >", value, "productCount");
            return (Criteria) this;
        }

        public Criteria andProductCountGreaterThanOrEqualTo(String value) {
            addCriterion("productCount >=", value, "productCount");
            return (Criteria) this;
        }

        public Criteria andProductCountLessThan(String value) {
            addCriterion("productCount <", value, "productCount");
            return (Criteria) this;
        }

        public Criteria andProductCountLessThanOrEqualTo(String value) {
            addCriterion("productCount <=", value, "productCount");
            return (Criteria) this;
        }

        public Criteria andProductCountLike(String value) {
            addCriterion("productCount like", value, "productCount");
            return (Criteria) this;
        }

        public Criteria andProductCountNotLike(String value) {
            addCriterion("productCount not like", value, "productCount");
            return (Criteria) this;
        }

        public Criteria andProductCountIn(List<String> values) {
            addCriterion("productCount in", values, "productCount");
            return (Criteria) this;
        }

        public Criteria andProductCountNotIn(List<String> values) {
            addCriterion("productCount not in", values, "productCount");
            return (Criteria) this;
        }

        public Criteria andProductCountBetween(String value1, String value2) {
            addCriterion("productCount between", value1, value2, "productCount");
            return (Criteria) this;
        }

        public Criteria andProductCountNotBetween(String value1, String value2) {
            addCriterion("productCount not between", value1, value2, "productCount");
            return (Criteria) this;
        }

        public Criteria andShopUrlIsNull() {
            addCriterion("shopUrl is null");
            return (Criteria) this;
        }

        public Criteria andShopUrlIsNotNull() {
            addCriterion("shopUrl is not null");
            return (Criteria) this;
        }

        public Criteria andShopUrlEqualTo(String value) {
            addCriterion("shopUrl =", value, "shopUrl");
            return (Criteria) this;
        }

        public Criteria andShopUrlNotEqualTo(String value) {
            addCriterion("shopUrl <>", value, "shopUrl");
            return (Criteria) this;
        }

        public Criteria andShopUrlGreaterThan(String value) {
            addCriterion("shopUrl >", value, "shopUrl");
            return (Criteria) this;
        }

        public Criteria andShopUrlGreaterThanOrEqualTo(String value) {
            addCriterion("shopUrl >=", value, "shopUrl");
            return (Criteria) this;
        }

        public Criteria andShopUrlLessThan(String value) {
            addCriterion("shopUrl <", value, "shopUrl");
            return (Criteria) this;
        }

        public Criteria andShopUrlLessThanOrEqualTo(String value) {
            addCriterion("shopUrl <=", value, "shopUrl");
            return (Criteria) this;
        }

        public Criteria andShopUrlLike(String value) {
            addCriterion("shopUrl like", value, "shopUrl");
            return (Criteria) this;
        }

        public Criteria andShopUrlNotLike(String value) {
            addCriterion("shopUrl not like", value, "shopUrl");
            return (Criteria) this;
        }

        public Criteria andShopUrlIn(List<String> values) {
            addCriterion("shopUrl in", values, "shopUrl");
            return (Criteria) this;
        }

        public Criteria andShopUrlNotIn(List<String> values) {
            addCriterion("shopUrl not in", values, "shopUrl");
            return (Criteria) this;
        }

        public Criteria andShopUrlBetween(String value1, String value2) {
            addCriterion("shopUrl between", value1, value2, "shopUrl");
            return (Criteria) this;
        }

        public Criteria andShopUrlNotBetween(String value1, String value2) {
            addCriterion("shopUrl not between", value1, value2, "shopUrl");
            return (Criteria) this;
        }

        public Criteria andShopRealUrlIsNull() {
            addCriterion("shopRealUrl is null");
            return (Criteria) this;
        }

        public Criteria andShopRealUrlIsNotNull() {
            addCriterion("shopRealUrl is not null");
            return (Criteria) this;
        }

        public Criteria andShopRealUrlEqualTo(String value) {
            addCriterion("shopRealUrl =", value, "shopRealUrl");
            return (Criteria) this;
        }

        public Criteria andShopRealUrlNotEqualTo(String value) {
            addCriterion("shopRealUrl <>", value, "shopRealUrl");
            return (Criteria) this;
        }

        public Criteria andShopRealUrlGreaterThan(String value) {
            addCriterion("shopRealUrl >", value, "shopRealUrl");
            return (Criteria) this;
        }

        public Criteria andShopRealUrlGreaterThanOrEqualTo(String value) {
            addCriterion("shopRealUrl >=", value, "shopRealUrl");
            return (Criteria) this;
        }

        public Criteria andShopRealUrlLessThan(String value) {
            addCriterion("shopRealUrl <", value, "shopRealUrl");
            return (Criteria) this;
        }

        public Criteria andShopRealUrlLessThanOrEqualTo(String value) {
            addCriterion("shopRealUrl <=", value, "shopRealUrl");
            return (Criteria) this;
        }

        public Criteria andShopRealUrlLike(String value) {
            addCriterion("shopRealUrl like", value, "shopRealUrl");
            return (Criteria) this;
        }

        public Criteria andShopRealUrlNotLike(String value) {
            addCriterion("shopRealUrl not like", value, "shopRealUrl");
            return (Criteria) this;
        }

        public Criteria andShopRealUrlIn(List<String> values) {
            addCriterion("shopRealUrl in", values, "shopRealUrl");
            return (Criteria) this;
        }

        public Criteria andShopRealUrlNotIn(List<String> values) {
            addCriterion("shopRealUrl not in", values, "shopRealUrl");
            return (Criteria) this;
        }

        public Criteria andShopRealUrlBetween(String value1, String value2) {
            addCriterion("shopRealUrl between", value1, value2, "shopRealUrl");
            return (Criteria) this;
        }

        public Criteria andShopRealUrlNotBetween(String value1, String value2) {
            addCriterion("shopRealUrl not between", value1, value2, "shopRealUrl");
            return (Criteria) this;
        }

        public Criteria andGoodratePercentIsNull() {
            addCriterion("goodratePercent is null");
            return (Criteria) this;
        }

        public Criteria andGoodratePercentIsNotNull() {
            addCriterion("goodratePercent is not null");
            return (Criteria) this;
        }

        public Criteria andGoodratePercentEqualTo(String value) {
            addCriterion("goodratePercent =", value, "goodratePercent");
            return (Criteria) this;
        }

        public Criteria andGoodratePercentNotEqualTo(String value) {
            addCriterion("goodratePercent <>", value, "goodratePercent");
            return (Criteria) this;
        }

        public Criteria andGoodratePercentGreaterThan(String value) {
            addCriterion("goodratePercent >", value, "goodratePercent");
            return (Criteria) this;
        }

        public Criteria andGoodratePercentGreaterThanOrEqualTo(String value) {
            addCriterion("goodratePercent >=", value, "goodratePercent");
            return (Criteria) this;
        }

        public Criteria andGoodratePercentLessThan(String value) {
            addCriterion("goodratePercent <", value, "goodratePercent");
            return (Criteria) this;
        }

        public Criteria andGoodratePercentLessThanOrEqualTo(String value) {
            addCriterion("goodratePercent <=", value, "goodratePercent");
            return (Criteria) this;
        }

        public Criteria andGoodratePercentLike(String value) {
            addCriterion("goodratePercent like", value, "goodratePercent");
            return (Criteria) this;
        }

        public Criteria andGoodratePercentNotLike(String value) {
            addCriterion("goodratePercent not like", value, "goodratePercent");
            return (Criteria) this;
        }

        public Criteria andGoodratePercentIn(List<String> values) {
            addCriterion("goodratePercent in", values, "goodratePercent");
            return (Criteria) this;
        }

        public Criteria andGoodratePercentNotIn(List<String> values) {
            addCriterion("goodratePercent not in", values, "goodratePercent");
            return (Criteria) this;
        }

        public Criteria andGoodratePercentBetween(String value1, String value2) {
            addCriterion("goodratePercent between", value1, value2, "goodratePercent");
            return (Criteria) this;
        }

        public Criteria andGoodratePercentNotBetween(String value1, String value2) {
            addCriterion("goodratePercent not between", value1, value2, "goodratePercent");
            return (Criteria) this;
        }

        public Criteria andMainAuctionIsNull() {
            addCriterion("mainAuction is null");
            return (Criteria) this;
        }

        public Criteria andMainAuctionIsNotNull() {
            addCriterion("mainAuction is not null");
            return (Criteria) this;
        }

        public Criteria andMainAuctionEqualTo(String value) {
            addCriterion("mainAuction =", value, "mainAuction");
            return (Criteria) this;
        }

        public Criteria andMainAuctionNotEqualTo(String value) {
            addCriterion("mainAuction <>", value, "mainAuction");
            return (Criteria) this;
        }

        public Criteria andMainAuctionGreaterThan(String value) {
            addCriterion("mainAuction >", value, "mainAuction");
            return (Criteria) this;
        }

        public Criteria andMainAuctionGreaterThanOrEqualTo(String value) {
            addCriterion("mainAuction >=", value, "mainAuction");
            return (Criteria) this;
        }

        public Criteria andMainAuctionLessThan(String value) {
            addCriterion("mainAuction <", value, "mainAuction");
            return (Criteria) this;
        }

        public Criteria andMainAuctionLessThanOrEqualTo(String value) {
            addCriterion("mainAuction <=", value, "mainAuction");
            return (Criteria) this;
        }

        public Criteria andMainAuctionLike(String value) {
            addCriterion("mainAuction like", value, "mainAuction");
            return (Criteria) this;
        }

        public Criteria andMainAuctionNotLike(String value) {
            addCriterion("mainAuction not like", value, "mainAuction");
            return (Criteria) this;
        }

        public Criteria andMainAuctionIn(List<String> values) {
            addCriterion("mainAuction in", values, "mainAuction");
            return (Criteria) this;
        }

        public Criteria andMainAuctionNotIn(List<String> values) {
            addCriterion("mainAuction not in", values, "mainAuction");
            return (Criteria) this;
        }

        public Criteria andMainAuctionBetween(String value1, String value2) {
            addCriterion("mainAuction between", value1, value2, "mainAuction");
            return (Criteria) this;
        }

        public Criteria andMainAuctionNotBetween(String value1, String value2) {
            addCriterion("mainAuction not between", value1, value2, "mainAuction");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("location is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("location is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("location =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("location <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("location >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("location >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("location <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("location <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("location like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("location not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("location in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("location not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("location between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("location not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andTelephoneIsNull() {
            addCriterion("telephone is null");
            return (Criteria) this;
        }

        public Criteria andTelephoneIsNotNull() {
            addCriterion("telephone is not null");
            return (Criteria) this;
        }

        public Criteria andTelephoneEqualTo(String value) {
            addCriterion("telephone =", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotEqualTo(String value) {
            addCriterion("telephone <>", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneGreaterThan(String value) {
            addCriterion("telephone >", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("telephone >=", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLessThan(String value) {
            addCriterion("telephone <", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLessThanOrEqualTo(String value) {
            addCriterion("telephone <=", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLike(String value) {
            addCriterion("telephone like", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotLike(String value) {
            addCriterion("telephone not like", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneIn(List<String> values) {
            addCriterion("telephone in", values, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotIn(List<String> values) {
            addCriterion("telephone not in", values, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneBetween(String value1, String value2) {
            addCriterion("telephone between", value1, value2, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotBetween(String value1, String value2) {
            addCriterion("telephone not between", value1, value2, "telephone");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("category like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("category not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("category not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andDestinationIsNull() {
            addCriterion("destination is null");
            return (Criteria) this;
        }

        public Criteria andDestinationIsNotNull() {
            addCriterion("destination is not null");
            return (Criteria) this;
        }

        public Criteria andDestinationEqualTo(String value) {
            addCriterion("destination =", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationNotEqualTo(String value) {
            addCriterion("destination <>", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationGreaterThan(String value) {
            addCriterion("destination >", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationGreaterThanOrEqualTo(String value) {
            addCriterion("destination >=", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationLessThan(String value) {
            addCriterion("destination <", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationLessThanOrEqualTo(String value) {
            addCriterion("destination <=", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationLike(String value) {
            addCriterion("destination like", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationNotLike(String value) {
            addCriterion("destination not like", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationIn(List<String> values) {
            addCriterion("destination in", values, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationNotIn(List<String> values) {
            addCriterion("destination not in", values, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationBetween(String value1, String value2) {
            addCriterion("destination between", value1, value2, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationNotBetween(String value1, String value2) {
            addCriterion("destination not between", value1, value2, "destination");
            return (Criteria) this;
        }

        public Criteria andAllkeysIsNull() {
            addCriterion("allkeys is null");
            return (Criteria) this;
        }

        public Criteria andAllkeysIsNotNull() {
            addCriterion("allkeys is not null");
            return (Criteria) this;
        }

        public Criteria andAllkeysEqualTo(String value) {
            addCriterion("allkeys =", value, "allkeys");
            return (Criteria) this;
        }

        public Criteria andAllkeysNotEqualTo(String value) {
            addCriterion("allkeys <>", value, "allkeys");
            return (Criteria) this;
        }

        public Criteria andAllkeysGreaterThan(String value) {
            addCriterion("allkeys >", value, "allkeys");
            return (Criteria) this;
        }

        public Criteria andAllkeysGreaterThanOrEqualTo(String value) {
            addCriterion("allkeys >=", value, "allkeys");
            return (Criteria) this;
        }

        public Criteria andAllkeysLessThan(String value) {
            addCriterion("allkeys <", value, "allkeys");
            return (Criteria) this;
        }

        public Criteria andAllkeysLessThanOrEqualTo(String value) {
            addCriterion("allkeys <=", value, "allkeys");
            return (Criteria) this;
        }

        public Criteria andAllkeysLike(String value) {
            addCriterion("allkeys like", value, "allkeys");
            return (Criteria) this;
        }

        public Criteria andAllkeysNotLike(String value) {
            addCriterion("allkeys not like", value, "allkeys");
            return (Criteria) this;
        }

        public Criteria andAllkeysIn(List<String> values) {
            addCriterion("allkeys in", values, "allkeys");
            return (Criteria) this;
        }

        public Criteria andAllkeysNotIn(List<String> values) {
            addCriterion("allkeys not in", values, "allkeys");
            return (Criteria) this;
        }

        public Criteria andAllkeysBetween(String value1, String value2) {
            addCriterion("allkeys between", value1, value2, "allkeys");
            return (Criteria) this;
        }

        public Criteria andAllkeysNotBetween(String value1, String value2) {
            addCriterion("allkeys not between", value1, value2, "allkeys");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateUserIsNull() {
            addCriterion("DataChange_CreateUser is null");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateUserIsNotNull() {
            addCriterion("DataChange_CreateUser is not null");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateUserEqualTo(String value) {
            addCriterion("DataChange_CreateUser =", value, "dataChange_CreateUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateUserNotEqualTo(String value) {
            addCriterion("DataChange_CreateUser <>", value, "dataChange_CreateUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateUserGreaterThan(String value) {
            addCriterion("DataChange_CreateUser >", value, "dataChange_CreateUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("DataChange_CreateUser >=", value, "dataChange_CreateUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateUserLessThan(String value) {
            addCriterion("DataChange_CreateUser <", value, "dataChange_CreateUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateUserLessThanOrEqualTo(String value) {
            addCriterion("DataChange_CreateUser <=", value, "dataChange_CreateUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateUserLike(String value) {
            addCriterion("DataChange_CreateUser like", value, "dataChange_CreateUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateUserNotLike(String value) {
            addCriterion("DataChange_CreateUser not like", value, "dataChange_CreateUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateUserIn(List<String> values) {
            addCriterion("DataChange_CreateUser in", values, "dataChange_CreateUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateUserNotIn(List<String> values) {
            addCriterion("DataChange_CreateUser not in", values, "dataChange_CreateUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateUserBetween(String value1, String value2) {
            addCriterion("DataChange_CreateUser between", value1, value2, "dataChange_CreateUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateUserNotBetween(String value1, String value2) {
            addCriterion("DataChange_CreateUser not between", value1, value2, "dataChange_CreateUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateTimeIsNull() {
            addCriterion("DataChange_CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateTimeIsNotNull() {
            addCriterion("DataChange_CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateTimeEqualTo(Date value) {
            addCriterion("DataChange_CreateTime =", value, "dataChange_CreateTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateTimeNotEqualTo(Date value) {
            addCriterion("DataChange_CreateTime <>", value, "dataChange_CreateTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateTimeGreaterThan(Date value) {
            addCriterion("DataChange_CreateTime >", value, "dataChange_CreateTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DataChange_CreateTime >=", value, "dataChange_CreateTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateTimeLessThan(Date value) {
            addCriterion("DataChange_CreateTime <", value, "dataChange_CreateTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("DataChange_CreateTime <=", value, "dataChange_CreateTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateTimeIn(List<Date> values) {
            addCriterion("DataChange_CreateTime in", values, "dataChange_CreateTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateTimeNotIn(List<Date> values) {
            addCriterion("DataChange_CreateTime not in", values, "dataChange_CreateTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateTimeBetween(Date value1, Date value2) {
            addCriterion("DataChange_CreateTime between", value1, value2, "dataChange_CreateTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_CreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("DataChange_CreateTime not between", value1, value2, "dataChange_CreateTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastUserIsNull() {
            addCriterion("DataChange_LastUser is null");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastUserIsNotNull() {
            addCriterion("DataChange_LastUser is not null");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastUserEqualTo(String value) {
            addCriterion("DataChange_LastUser =", value, "dataChange_LastUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastUserNotEqualTo(String value) {
            addCriterion("DataChange_LastUser <>", value, "dataChange_LastUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastUserGreaterThan(String value) {
            addCriterion("DataChange_LastUser >", value, "dataChange_LastUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastUserGreaterThanOrEqualTo(String value) {
            addCriterion("DataChange_LastUser >=", value, "dataChange_LastUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastUserLessThan(String value) {
            addCriterion("DataChange_LastUser <", value, "dataChange_LastUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastUserLessThanOrEqualTo(String value) {
            addCriterion("DataChange_LastUser <=", value, "dataChange_LastUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastUserLike(String value) {
            addCriterion("DataChange_LastUser like", value, "dataChange_LastUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastUserNotLike(String value) {
            addCriterion("DataChange_LastUser not like", value, "dataChange_LastUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastUserIn(List<String> values) {
            addCriterion("DataChange_LastUser in", values, "dataChange_LastUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastUserNotIn(List<String> values) {
            addCriterion("DataChange_LastUser not in", values, "dataChange_LastUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastUserBetween(String value1, String value2) {
            addCriterion("DataChange_LastUser between", value1, value2, "dataChange_LastUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastUserNotBetween(String value1, String value2) {
            addCriterion("DataChange_LastUser not between", value1, value2, "dataChange_LastUser");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastTimeIsNull() {
            addCriterion("DataChange_LastTime is null");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastTimeIsNotNull() {
            addCriterion("DataChange_LastTime is not null");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastTimeEqualTo(Date value) {
            addCriterion("DataChange_LastTime =", value, "dataChange_LastTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastTimeNotEqualTo(Date value) {
            addCriterion("DataChange_LastTime <>", value, "dataChange_LastTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastTimeGreaterThan(Date value) {
            addCriterion("DataChange_LastTime >", value, "dataChange_LastTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DataChange_LastTime >=", value, "dataChange_LastTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastTimeLessThan(Date value) {
            addCriterion("DataChange_LastTime <", value, "dataChange_LastTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastTimeLessThanOrEqualTo(Date value) {
            addCriterion("DataChange_LastTime <=", value, "dataChange_LastTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastTimeIn(List<Date> values) {
            addCriterion("DataChange_LastTime in", values, "dataChange_LastTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastTimeNotIn(List<Date> values) {
            addCriterion("DataChange_LastTime not in", values, "dataChange_LastTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastTimeBetween(Date value1, Date value2) {
            addCriterion("DataChange_LastTime between", value1, value2, "dataChange_LastTime");
            return (Criteria) this;
        }

        public Criteria andDataChange_LastTimeNotBetween(Date value1, Date value2) {
            addCriterion("DataChange_LastTime not between", value1, value2, "dataChange_LastTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dianpu
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 15 19:01:58 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dianpu
     *
     * @mbggenerated Fri Sep 15 19:01:58 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}